// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggsyxvphirxptyphcrnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnc3l4dnBoaXJ4cHR5cGhjcm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDQyNDcsImV4cCI6MjA2NTk4MDI0N30.RG_m5cxQ0z5AVYMqEFLFSKAc_c1cwbm5Mx3mcyewWDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);